[project]
name = 'SmartParking'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.SmartParking]
path = 'contracts/SmartParking.clar'
clarity_version = 3
epoch = 3.1

[contracts.GroupBooking]
path = 'contracts/GroupBooking.clar'
clarity_version = 3
epoch = 3.1

[contracts.ParkingAuctions]
path = 'contracts/ParkingAuctions.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
